export const fakeData = [
  {
    id: 1,
    name: "Vuelta en kayak en Tigre",
    city: "Tigre",
    category: "Acuatico",
    price: "5000",
    rating: "7,8",
    comentarios: [
      {
        userID: 2,
        commentario: "commentario experiencia user 2",
      },
    ],
    description: "Description actividad",
    stock: 19,
    img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
    provincia: "Buenos Aires",
    historial: [],
  },
  {
    id: 2,
    name: "Trekking Fin del Mundo - Ushuaia, Tierra del Fuego",
    city: "Ushuaia",
    category: "Trekking",
    price: "15000",
    rating: "5,8",
    comentarios: [
      {
        userID: 2,
        commentario: "commentario experiencia user 2",
      },
      {
        userID: 1,
        commentario: "commentario experiencia user 1",
      },
    ],
    description: "Description actividad",
    stock: 19,
    img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
    provincia: "Buenos Aires",
    historial: [],
  },
  {
    id: 3,
    name: "Vuelta en kayak en Tigre",
    city: "Tigre",
    category: "Acuatico",
    price: "5000",
    rating: "7,8",
    comentarios: [
      {
        userID: 2,
        commentario: "commentario experiencia user 2",
      },
    ],
    description: "Description actividad",
    stock: 19,
    img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
    provincia: "Buenos Aires",
    historial: [],
  },
  {
    id: 4,
    name: "Vuelta en kayak en Tigre",
    city: "Tigre",
    category: "Acuatico",
    price: "5000",
    rating: "7,8",
    comentarios: [
      {
        userID: 2,
        commentario: "commentario experiencia user 2",
      },
    ],
    description: "Description actividad",
    stock: 19,
    img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
    provincia: "Buenos Aires",
    historial: [],
  },
  {
    id: 5,
    name: "Vuelta en kayak en Tigre",
    city: "Tigre",
    category: "Acuatico",
    price: "5000",
    rating: "7,8",
    comentarios: [
      {
        userID: 2,
        commentario: "commentario experiencia user 2",
      },
    ],
    description: "Description actividad",
    stock: 19,
    img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
    provincia: "Buenos Aires",
    historial: [],
  },
  {
    id: 6,
    name: "Vuelta en kayak en Tigre",
    city: "Tigre",
    category: "Acuatico",
    price: "5000",
    rating: "7,8",
    comentarios: [
      {
        userID: 2,
        commentario: "commentario experiencia user 2",
      },
    ],
    description: "Description actividad",
    stock: 19,
    img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
    provincia: "Buenos Aires",
    historial: [],
  },
  {
    id: 7,
    name: "Vuelta en kayak en Tigre",
    city: "Tigre",
    category: "Acuatico",
    price: "5000",
    rating: "7,8",
    comentarios: [
      {
        userID: 2,
        commentario: "commentario experiencia user 2",
      },
    ],
    description: "Description actividad",
    stock: 19,
    img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
    provincia: "Buenos Aires",
    historial: [],
  },
  {
    id: 8,
    name: "Vuelta en kayak en Tigre",
    city: "Tigre",
    category: "Acuatico",
    price: "5000",
    rating: "7,8",
    comentarios: [
      {
        userID: 2,
        commentario: "commentario experiencia user 2",
      },
    ],
    description: "Description actividad",
    stock: 19,
    img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
    provincia: "Buenos Aires",
    historial: [],
  },
  {
    id: 9,
    name: "Vuelta en kayak en Tigre",
    city: "Tigre",
    category: "Acuatico",
    price: "5000",
    rating: "7,8",
    comentarios: [
      {
        userID: 2,
        commentario: "commentario experiencia user 2",
      },
    ],
    description: "Description actividad",
    stock: 19,
    img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
    provincia: "Buenos Aires",
    historial: [],
  },
  {
    id: 10,
    name: "Vuelta en kayak en Tigre",
    city: "Tigre",
    category: "Acuatico",
    price: "5000",
    rating: "7,8",
    comentarios: [
      {
        userID: 2,
        commentario: "commentario experiencia user 2",
      },
    ],
    description: "Description actividad",
    stock: 19,
    img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
    provincia: "Buenos Aires",
    historial: [],
  },
];

 const carrito = [
  {
    producto: {
      id: 1,
      name: "Vuelta en kayak en Tigre",
      city: "Tigre",
      category: "Acuatico",
      price: "5000",
      rating: "7,8",
      comentarios: [
        {
          userID: 2,
          commentario: "commentario experiencia user 2",
        },
      ],
      description: "Description actividad",
      stock: 19,
      img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
      provincia: "Buenos Aires",
      historial: [],
    },
    cantidad: 1,
  },
  {
    producto: {
      id: 2,
      name: "Vuelta en kayak en Tigre",
      city: "Tigre",
      category: "Acuatico",
      price: "5000",
      rating: "7,8",
      comentarios: [
        {
          userID: 2,
          commentario: "commentario experiencia user 2",
        },
      ],
      description: "Description actividad",
      stock: 19,
      img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
      provincia: "Buenos Aires",
      historial: [],
    },
    cantidad: 2,
  },
  {
    producto: {
      id: 3,
      name: "Vuelta en kayak en Tigre",
      city: "Tigre",
      category: "Acuatico",
      price: "5000",
      rating: "7,8",
      comentarios: [
        {
          userID: 2,
          commentario: "commentario experiencia user 2",
        },
      ],
      description: "Description actividad",
      stock: 19,
      img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
      provincia: "Buenos Aires",
      historial: [],
    },
    cantidad: 3,
  },
  {
    producto: {
      id: 4,
      name: "Vuelta en kayak en Tigre",
      city: "Tigre",
      category: "Acuatico",
      price: "5000",
      rating: "7,8",
      comentarios: [
        {
          userID: 2,
          commentario: "commentario experiencia user 2",
        },
      ],
      description: "Description actividad",
      stock: 19,
      img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
      provincia: "Buenos Aires",
      historial: [],
    },
    cantidad: 21,
  },
  {
    producto: {
      id: 5,
      name: "Vuelta en kayak en Tigre",
      city: "Tigre",
      category: "Acuatico",
      price: "5000",
      rating: "7,8",
      comentarios: [
        {
          userID: 2,
          commentario: "commentario experiencia user 2",
        },
      ],
      description: "Description actividad",
      stock: 19,
      img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
      provincia: "Buenos Aires",
      historial: [],
    },
    cantidad: 28,
  },
  {
    producto: {
      id: 6,
      name: "Vuelta en kayak en Tigre",
      city: "Tigre",
      category: "Acuatico",
      price: "5000",
      rating: "7,8",
      comentarios: [
        {
          userID: 2,
          commentario: "commentario experiencia user 2",
        },
      ],
      description: "Description actividad",
      stock: 19,
      img: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Sea_Kayak.JPG",
      provincia: "Buenos Aires",
      historial: [],
    },
    cantidad: 20,
  },
];

export const setCarrito = () => {localStorage.setItem("carrito", JSON.stringify(carrito))}
